spring.application.name=${SPRING_APPLICATION_NAME:payment-system}

# mysql setting
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/sparta_payment?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}

# JPA/Hibernate setting
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}

# PortOne API Configuration
portone.api.secret=${PORTONE_API_SECRET:AIfgWrJzG2QrvEIk9Cqt7Smj1NrtbYsiqIGktexuQRp3M5onC9tMCJOPdKrOzVQLHTxaECqksO4qytxS}
portone.api.url=${PORTONE_API_URL:https://api.portone.io}

# KG inicis with portone
portone.store.id=${PORTONE_STORE_ID:store-4fd347dd-42c3-4070-a1db-d16bae14b7e2}
portone.channel.key=${PORTONE_CHANNEL_KEY:channel-key-7d3eacb5-9c50-47bb-a3e4-5888815d0a5b}
portone.pg.mid=${PORTONE_PG_MID:INIpayTest}
portone.web.signkey=${PORTONE_WEB_SIGNKEY:SU5JTElURV9UUklQTEVERVNfS0VZU1RS}
portone.ini.api.key=${PORTONE_INI_API_KEY:ItEQKi3rY7uvDS8l}
portone.ini.api.iv=${PORTONE_INI_API_IV:HYb3yQ4f65QL89==}

# portone webhook
portone.webhook.secret=${PORTONE_WEBHOOK_SECRET:whsec_yRTH0nqL0pJPSEtaomU9XrLlUUpr4BjGLyRekBxJ1rg=}